Repository dev-cafe/parselglossy, pull requests merged in 2019-03, with the labels that each got.

#13 Documentation
  docs/conf.py
  docs/design.rst
  docs/gfx/parselglossy.jpg
  docs/gfx/validator.png
  docs/index.rst
  docs/requirements.txt
Labels: documentation

#8 Getkw grammar
  .envrc
  .githooks/LICENSE-Python
  .githooks/license_maintainer.py
  .gitignore
  .style.yapf
  CONTRIBUTING.rst
  Pipfile
  docs/conf.py
  parselglossy/__init__.py
  parselglossy/atoms.py
  parselglossy/cli.py
  parselglossy/getkw.py
  parselglossy/getkw_grammar.py
  parselglossy/standard_grammar.py
  parselglossy/token_actions.py
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_atoms.py
  tests/test_cli.py
  tests/test_getkw.py
  tests/test_parselglossy.py
  tests/test_standard_grammar.py
  tox.ini
Labels: enhancement

#20 Validate input against a template; closes #2.
  .ci/azure-steps.yml
  .travis.yml
  Pipfile
  parselglossy/read_yaml.py
  parselglossy/validate.py
  setup.py
  tests/test_types.py
  tests/test_validation.py
  tests/validation/input_errors/input_missing_keyword.yml
  tests/validation/input_errors/input_predicate_cross.yml
  tests/validation/input_errors/input_predicate_intra.yml
  tests/validation/input_errors/input_type_error_bool.yml
  tests/validation/input_errors/input_type_error_float.yml
  tests/validation/input_errors/input_type_error_int.yml
  tests/validation/input_errors/input_type_error_list.yml
  tests/validation/input_errors/input_type_error_str.yml
  tests/validation/input_errors/input_unexpected_keyword.yml
  tests/validation/input_errors/input_unexpected_section.yml
  tests/validation/input_errors/template.yml
  tests/validation/overall/input.yml
  tests/validation/overall/template.yml
  tests/validation/template_errors/input.yml
  tests/validation/template_errors/template_empty_documentation.yml
  tests/validation/template_errors/template_invalid_predicate.yml
  tests/validation/template_errors/template_no_documentation.yml
Labels: enhancement

#39 Remove some dev deps
  .githooks/pre-commit
  .githooks/pre-commit-black
  CONTRIBUTING.rst
  Pipfile
  setup.cfg
  tests/test_getkw.py
Labels: lowprio
